CREATE TABLE IF NOT EXISTS companies (
    id SERIAL PRIMARY KEY,
    company_name VARCHAR(255),
    num_employees INT,
    industry VARCHAR(255),
    website VARCHAR(500),
    company_linkedin_url VARCHAR(500) UNIQUE, -- Add UNIQUE constraint here
    facebook_url VARCHAR(500),
    twitter_url VARCHAR(500),
    company_street VARCHAR(255),
    company_city VARCHAR(255),
    company_state VARCHAR(255),
    company_country VARCHAR(255),
    company_postal_code VARCHAR(50),
    company_address TEXT,
    keywords TEXT,
    company_phone VARCHAR(50),
    seo_description TEXT,
    technologies TEXT,
    total_funding VARCHAR(100),
    latest_funding VARCHAR(100),
    latest_funding_amount VARCHAR(100),
    last_raised_at DATE,
    annual_revenue VARCHAR(100),
    num_retail_locations INT,
    sic_codes VARCHAR(255),
    short_description TEXT,
    founded_year INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);