CREATE TABLE IF NOT EXISTS companies (
    id SERIAL PRIMARY KEY,
    company_name TEXT,
    num_employees INT,
    industry TEXT,
    website TEXT,
    company_linkedin_url TEXT UNIQUE,
    facebook_url TEXT,
    twitter_url TEXT,
    company_street TEXT,
    company_city TEXT,
    company_state TEXT,
    company_country TEXT,
    company_postal_code TEXT,
    company_address TEXT,
    keywords TEXT,
    company_phone TEXT,
    seo_description TEXT,
    technologies TEXT,
    total_funding TEXT,
    latest_funding TEXT,
    latest_funding_amount TEXT,
    last_raised_at TEXT,
    annual_revenue TEXT,
    num_retail_locations INT,
    sic_codes TEXT,
    short_description TEXT,
    founded_year INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
