CREATE TABLE IF NOT EXISTS peopleLeads (
    id SERIAL PRIMARY KEY,
    first_name TEXT,
    last_name TEXT,
    title TEXT,
    company TEXT,
    email TEXT,
    email_status TEXT,
    seniority TEXT,
    departments TEXT,
    work_direct_phone TEXT,
    mobile_phone TEXT,
    corporate_phone TEXT,
    phone TEXT,
    category TEXT,
    organization TEXT,
    position TEXT,
    country TEXT,
    city TEXT,
    state TEXT,
    company_address TEXT,
    company_city TEXT,
    company_state TEXT,
    company_country TEXT,
    industry TEXT,
    num_employees INT,
    linkedin_url TEXT UNIQUE,
    website TEXT,
    company_linkedin_url TEXT,
    facebook_url TEXT,
    twitter_url TEXT,
    keywords TEXT,
    technologies TEXT,
    seo_description TEXT,
    annual_revenue TEXT,
    total_funding TEXT,
    latest_funding TEXT,
    latest_funding_amount TEXT,
    last_raised_at TEXT,
    num_retail_locations INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
