CREATE TABLE IF NOT EXISTS peopleLeads (
    id SERIAL PRIMARY KEY,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    title VARCHAR(255),
    company VARCHAR(255),
    email VARCHAR(255),
    email_status VARCHAR(100),
    seniority VARCHAR(100),
    departments VARCHAR(255),
    work_direct_phone VARCHAR(50),
    mobile_phone VARCHAR(50),
    corporate_phone VARCHAR(50),
    phone VARCHAR(50),
    category VARCHAR(255),
    organization VARCHAR(255),
    position VARCHAR(255),
    country VARCHAR(100),
    city VARCHAR(100),
    state VARCHAR(100),
    company_address TEXT,
    company_city VARCHAR(100),
    company_state VARCHAR(100),
    company_country VARCHAR(100),
    industry VARCHAR(255),
    num_employees INT,
    linkedin_url VARCHAR(500) UNIQUE,
    website VARCHAR(500),
    company_linkedin_url VARCHAR(500),
    facebook_url VARCHAR(500),
    twitter_url VARCHAR(500),
    keywords TEXT,
    technologies TEXT,
    seo_description TEXT,
    annual_revenue VARCHAR(100),
    total_funding VARCHAR(100),
    latest_funding VARCHAR(100),
    latest_funding_amount VARCHAR(100),
    last_raised_at VARCHAR(100),
    num_retail_locations INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);